import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Actor } from "next/font/google";

const actor = Actor({
  subsets: ["latin"],
  variable: "--actor",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={actor.className}>
        <Sidebar>{children}</Sidebar>
      </body>
    </html>
  );
}
